import { Textf, Button, Progress_Map } from "blocks.slint";

export component Main_Window inherits Window {
    Textf {
        text: "Ai horde manager!";
        font-size: 40px;
        y: 90px;
    }

    Textf {
        text: "Note that this is still a very early alpha, and this is just basic install functionality. More will be added later. \n\n\n You can check the logs for progress";
        wrap: word-wrap;
        width: root.width - 40px;
        y: 160px;
        font-size: 20px;
    }

    callback install();
    Button {
        y: 375px;
        width: 100px;
        Textf {
            text: "Install Horde";
        }

        clicked => {
            install()
        }
    }

    title: "Ai Horde Manager";
    preferred-height: 700px;
    preferred-width: 450px;
    min-height: 300px;
    min-width: 450px;
    background: #1f1f1f;
}
